(load "C:/Users/Juan/Documents/Practica2-IA/CLIPS/Ontologia.CLP")
(load "C:/Users/Juan/Documents/Practica2-IA/CLIPS/MAINMOD.CLP")
(load "C:/Users/Juan/Documents/Practica2-IA/CLIPS/ComplexityMod.CLP")
(load "C:/Users/Juan/Documents/Practica2-IA/CLIPS/PreguntasMod.CLP")
(load "C:/Users/Juan/Documents/Practica2-IA/CLIPS/HeuristicMod.CLP")
(load "C:/Users/Juan/Documents/Practica2-IA/CLIPS/ObsTimeMod.CLP")
(load "C:/Users/Juan/Documents/Practica2-IA/CLIPS/PaintIntMod.CLP")
(load "C:/Users/Juan/Documents/Practica2-IA/CLIPS/VisitaMod.CLP")
(load "C:/Users/Juan/Documents/Practica2-IA/CLIPS/CrearVisitaMod.CLP")
(load "C:/Users/Juan/Documents/Practica2-IA/CLIPS/SortMod.CLP")
(load "C:/Users/Juan/Documents/Practica2-IA/CLIPS/OrganizeMod.CLP")
(reset)
(run)