(load "Pon aqui tu ruta"/Practica2-IA/CLIPS/MAINMOD.CLP")
(load "Pon aqui tu ruta"/Practica2-IA/CLIPS/PreguntasMod.CLP")
(load "Pon aqui tu ruta"/Practica2-IA/CLIPS/HeuristicMod.CLP")
(load "Pon aqui tu ruta"/Practica2-IA/CLIPS/ObsTimeMod.CLP")
(load "Pon aqui tu ruta"/Practica2-IA/CLIPS/PaintIntMod.CLP")
(load "Pon aqui tu ruta"/Practica2-IA/CLIPS/CrearVisitaMod.CLP")
(reset)
(run)