(load "C:/Users/Fanz0/Desktop/Uni/5/IA/Practica2-IA/CLIPS/MAINMOD.CLP")
(load "C:/Users/Fanz0/Desktop/Uni/5/IA/Practica2-IA/CLIPS/PreguntasMod.CLP")
(load "C:/Users/Fanz0/Desktop/Uni/5/IA/Practica2-IA/CLIPS/HeuristicMod.CLP")
(load "C:/Users/Fanz0/Desktop/Uni/5/IA/Practica2-IA/CLIPS/ObsTimeMod.CLP")
(load "C:/Users/Fanz0/Desktop/Uni/5/IA/Practica2-IA/CLIPS/PaintIntMod.CLP")
(load "C:/Users/Fanz0/Desktop/Uni/5/IA/Practica2-IA/CLIPS/CrearVisitaMod.CLP")
(reset)
(run)