(load "F:/Assignaturas/IA/Practica2-IA/CLIPS/MAINMOD.CLP")
(load "F:/Assignaturas/IA/Practica2-IA/CLIPS/PreguntasMod.CLP")
(load "F:/Assignaturas/IA/Practica2-IA/CLIPS/HeuristicMod.CLP")
(load "F:/Assignaturas/IA/Practica2-IA/CLIPS/ObsTimeMod.CLP")
(load "F:/Assignaturas/IA/Practica2-IA/CLIPS/PaintIntMod.CLP")
(load "F:/Assignaturas/IA/Practica2-IA/CLIPS/SortMod.CLP")
(reset)
(run)