(load "F:/IA/Knowledge-Based-System-planner/src/CLIPS/Ontologia.CLP")
(load "F:/IA/Knowledge-Based-System-planner/src/CLIPS/MAINMOD.CLP")
(load "F:/IA/Knowledge-Based-System-planner/src/CLIPS/ComplexityMod.CLP")
(load "F:/IA/Knowledge-Based-System-planner/src/CLIPS/PreguntasMod.CLP")
(load "F:/IA/Knowledge-Based-System-planner/src/CLIPS/HeuristicMod.CLP")
(load "F:/IA/Knowledge-Based-System-planner/src/CLIPS/ObsTimeMod.CLP")
(load "F:/IA/Knowledge-Based-System-planner/src/CLIPS/PaintIntMod.CLP")
(load "F:/IA/Knowledge-Based-System-planner/src/CLIPS/VisitaMod.CLP")
(load "F:/IA/Knowledge-Based-System-planner/src/CLIPS/SortMod.CLP")
(load "F:/IA/Knowledge-Based-System-planner/src/CLIPS/CrearVisitaMod.CLP")
(load "F:/IA/Knowledge-Based-System-planner/src/CLIPS/OrganizeMod.CLP")
(reset)
(run)